---
- name: Copy global MariaDB configuration
  ansible.builtin.template:
    src: mariadb.cnf.j2
    dest: "{{ mariadb_config_file }}"
    owner: root
    group: root
    mode: 0644
    force: "{{ mariadb_overwrite_global_config_file }}"
  notify: Restart mariadb

- name: Does the data directory exists?
  ansible.builtin.stat:
    path: "{{ mariadb_data_dir }}"
  register: mariadb_custom_dir_stat

- name: Ensure data directory is present and accessible
  ansible.builtin.file:
    path: "{{ mariadb_data_dir }}"
    state: directory
    owner: "{{ mariadb_user }}"
    group: "{{ mariadb_group }}"
    mode: "{{ mariadb_datadir_permissions }}"

- name: Handle DB initialisation for an empty custom directory
  when: mariadb_custom_dir_stat.stat.isdir is not defined
  command: /usr/bin/mariadb-install-db --rpm --cross-bootstrap --user=mysql --disable-log-bin --skip-test-db

- name: Ensure MariaDB is started and enabled on boot
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: "{{ mariadb_enabled_on_startup }}"

- name: Immediately restart MariaDB (necessary for replication)
  ansible.builtin.meta: flush_handlers
